services:
  - type: web
    name: secure-auth-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "http://localhost:3000,http://localhost:5173,https://secure-auth-3.onrender.com,https://secure-auth-umber.vercel.app"
